// wolox-books/src/views/Login.vue
<template lang='pug'>
.container
  form.form-container(@submit.prevent='onSubmit' novalidate)
    img.wolox-image(src='../assets/wolox.png' alt='Wolox')
    .input-container
      label.input-label
        | Email
      input.input-field(type='email' v-model='email')
      span.errorMessage(v-if='$v.email.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Password
      input.input-field(type='password' v-model='password')
      span.errorMessage(v-if='$v.password.$invalid && submitted')
        | Invalid field. Upper letters and numbers are required.
    button.green-button(type='submit')
      | Log in
    router-link(to='/signup')
      button.grey-button(type='button')
        | Sign up
</template>

<script>
import { required, email } from 'vuelidate/lib/validators'
import { loginUser } from '../services/user-services'
import { validatePassword } from '../config/helpers'

export default {
  name: 'register',
  data () {
    return {
      email: null,
      password: null,
      locale: 'en',
      submitted: false
    }
  },
  methods: {
    onSubmit() {
      this.submitted = true
      if (!this.$v.$invalid) {
        const userData = {
          email: this.email,
          password: this.password
        }
        loginUser(userData)
        this.email = null
        this.password = null
        this.submitted = false
      }
    }
  },
  validations: {
    email: { required, email },
    password: { required, validatePassword }
  }
}
</script>

<style lang='scss'>
</style>

// wolox-books/src/app/screens/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators} from '@angular/forms';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';

import { UserService } from '../../services/user-service.service';

import { Validations } from '../../utils/validations';

import { AuthComponent } from '../../screens/auth/auth.component';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})

export class LoginComponent implements OnInit {

  signInForm: FormGroup;
  form:any;
  email:string = '';
  password:string = '';

  constructor(private fb: FormBuilder, private userService: UserService, private validation: Validations, private router: Router) {

    this.signInForm = fb.group({
      'email': [null, Validators.required],
      'password': [null, Validators.required]
    });
  };

  validEmail() {
    return this.validation.validEmail(this.signInForm.value.email);
  };

  submitLogin() {
    const session = {
      email: this.signInForm.value.email,
      password: this.signInForm.value.password
    }
    this.userService.loginUser(session);
    this.router.navigate(['auth']);
  };

  ngOnInit() {};
}

<form class="container sign-up" [formGroup]="signInForm" (ngSubmit)="submitLogin()">
  <div class="form-container sign-up">
    <div class="wolox-image">
      <img src="assets/wolox.png" alt="Wolox" class="wolox-image">
    </div>
    <div class="input-container">
      <label class="input-label"> Email </label>
      <input class="input-field" type="email" formControlName="email">
      <span class="alert" *ngIf="!signInForm.controls['email'].valid && signInForm.controls['email'].touched">
        Required field.
      </span>
      <span class="alert" *ngIf="signInForm.controls['email'].valid && signInForm.controls['email'].touched && !validEmail()">
        Invalid format.
      </span>
    </div>
    <div class="input-container">
      <label class="input-label"> Password </label>
      <input class="input-field" type="password" formControlName="password">
      <span class="alert" *ngIf="!signInForm.controls['password'].valid && signInForm.controls['password'].touched">
        Required field.
      </span>
    </div>
    <button class="button" type="submit" [disabled]="signInForm.invalid">Log in</button>
    <div class="green-button">
      <button class="button empty" routerLink="/sign-up" >Sign up</button>
    </div>
  </div>
</form>
