// wolox-books/src/app/screens/components/book-detail/book-detail.component.ts
import { Component, Input, OnInit } from '@angular/core';

@Component({
  selector: 'book-detail',
  templateUrl:'./book-detail.component.html',
  styleUrls: ['./book-detail.component.scss']
})

export class BookDetail implements OnInit {

  book: any;

  constructor() {};

  const book = {
    image_url: "https://via.placeholder.com/150",
    title: "Bella y graciosa mosa",
    gender: "Ficción",
    author: "J K Rowling",
    publisher: "Santillana",
    year: "1999"
  };


  /*@Input() books: any;

  bookSelected(bookId) {
    console.log("hubo un click en el book ID: " + bookId);
  };*/

  ngOnInit() {};

}

<div class="book-container row back-grey">
  <img src="{{book.image_url}}" alt="Book Image" class="book-image margin-20" (click)="bookSelected(book.id)">
  <div class="column width-100">
    <div class="row pad-20 under-green-line">
      <span class="bold text-1 pad-right-5">{{book.title}}</span>
      <span>{{book.gender}}</span>
    </div>
    <div class="pad-20">
      <div class="row pad-5">
        <span class="text-1 bold">Book Author: </span>
        <span class="text-1">{{book.author}}</span>
      </div>
      <div class="row pad-5">
        <span class="text-1 bold">Publisher: </span>
        <span class="text-1">{{book.publisher}}</span>
      </div>
      <div class="row pad-5">
        <span class="text-1 bold">Year of publication: </span>
        <span class="text-1">{{book.year}}</span>
      </div>
    </div>
  </div>
</div>

// wolox-books/src/views/BookDetail.vue
<template lang='pug'>
.book-container.row.back-grey
  img.book-image.margin-20(:src='selectedBook.image_url' :alt='selectedBook.title')
  .column.width-100
    .row.pad-20.under-green-line
      span.bold.text-ending.pad-right-5
        | {{selectedBook.title}}
      span.text-ending.pad-right-5
        | ({{selectedBook.genre}})
    .border
      .row.pad-5
        span.text-ending.bold
          | Book Author:
        span.text-ending
          | {{selectedBook.author}}
      .row.pad-5
        span.text-ending.bold
          | Publisher:
        span.text-ending
          | {{selectedBook.publisher}}
      .row.pad-5
        span.text-ending.bold
          | Year of publication:
        span.text-ending
          | {{selectedBook.year}}
</template>

<script>
import { mapActions, mapGetters } from 'vuex'

export default {
  methods: {
    ...mapActions(['bringSingleBook']),
    getBooks() {
      this.bringSingleBook()
    }
  },
  computed: {
    ...mapGetters(['selectedBook'])
  },
  beforeMount() {
    this.getBookInformation()
  }
}
</script>

<style scoped lang="scss">
@import '../scss/variables/colors';

.under-green-line {
  border-bottom: 2px solid $green-wolox;
}

.book-container {
  display: flex;
  max-width: 800px;
  margin: 30px auto;
  width: 100%;
  background-color: $white;
  height: auto;
}

.back-grey {
  background-color: $light-gray;
}

.border {
  margin: 20px 10px;
  padding: 10px 0;
}
</style>
