// wolox-books/src/app/screens/books/book-detail/book-detail.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router, ActivatedRoute, ParamMap } from '@angular/router';

import { HeaderComponent } from '../../components/header/header.component'
import { BooksService } from '../../../services/books-service.service';

@Component({
  selector: 'book-detail',
  templateUrl:'./book-detail.component.html',
  styleUrls: ['./book-detail.component.scss']
})

export class BookDetailComponent implements OnInit {

  book: any;

  constructor(private route: ActivatedRoute, private booksService: BooksService) {};

  bookSelected(bookId) {
    this.booksService.bringBookDetail(bookId).subscribe(response => {
      this.book = response;
    });
  };

  ngOnInit() {
    this.bookSelected(this.route.snapshot.params.id);
  };

}

<header-component></header-component>
<div class="book-container row back-grey">
  <img src="{{book.image_url}}" alt="Book Image" class="book-image margin-20" (click)="bookSelected(book.id)" i18n-alt>
  <div class="column width-100">
    <div class="row pad-20 under-green-line">
      <span class="bold text-1 pad-right-5">{{book.title}}</span>
      <span>({{book.genre}})</span>
    </div>
    <div class="pad-20">
      <div class="row pad-5">
        <span class="text-1 bold" i18n>Book Author: </span>
        <span class="text-1">{{book.author}}</span>
      </div>
      <div class="row pad-5">
        <span class="text-1 bold" i18n>Publisher: </span>
        <span class="text-1">{{book.publisher}}</span>
      </div>
      <div class="row pad-5">
        <span class="text-1 bold" i18n>Year of publication: </span>
        <span class="text-1">{{book.year}}</span>
      </div>
    </div>
  </div>
</div>

// wolox-books/src/views/BookDetail.vue
<template lang='pug'>
.book-container.row.back-grey
  img.book-image.margin-20(:src='selectedBook.image_url' :alt='selectedBook.title')
  .column.width-100
    .row.pad-20.under-green-line
      span.bold.text-ending.pad-right-5
        | {{selectedBook.title}}
      span.text-ending.pad-right-5
        | ({{selectedBook.genre}})
    .border
      .row.pad-5
        span.text-ending.bold
          | Book Author:
        span.text-ending
          | {{selectedBook.author}}
      .row.pad-5
        span.text-ending.bold
          | Publisher:
        span.text-ending
          | {{selectedBook.publisher}}
      .row.pad-5
        span.text-ending.bold
          | Year of publication:
        span.text-ending
          | {{selectedBook.year}}
</template>

<script>
import { mapActions, mapGetters } from 'vuex'

export default {
  methods: {
    ...mapActions(['bringSingleBook']),
    getBooks() {
      this.bringSingleBook()
    }
  },
  computed: {
    ...mapGetters(['selectedBook'])
  },
  beforeMount() {
    this.getBookInformation()
  }
}
</script>

<style scoped lang="scss">
@import '../scss/variables/colors';

.under-green-line {
  border-bottom: 2px solid $green-wolox;
}

.book-container {
  display: flex;
  max-width: 800px;
  margin: 30px auto;
  width: 100%;
  background-color: $white;
  height: auto;
}

.back-grey {
  background-color: $light-gray;
}

.border {
  margin: 20px 10px;
  padding: 10px 0;
}
</style>
