// wolox-books/src/app/screens/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators} from '@angular/forms';
import { UserService } from '../../services/user-service.service';
import { Validations } from '../../utils/validations';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  registrationForm: FormGroup;
  form:any;
  firstName:string = '';
  lastName:string = '';
  email:string = '';
  password:string = '';
  passwordConfirmation:string = '';

  constructor(private fb: FormBuilder, private userService: UserService, private validation: Validations ) {
    this.registrationForm = fb.group({
      'firstName': [null, Validators.required],
      'lastName': [null, Validators.required],
      'email': [null, Validators.required],
      'password': [null, Validators.required],
      'passwordConfirmation': [null, Validators.required]
    });
  };

  validEmail() {
    return this.validation.validEmail(this.registrationForm.value.email);
  };

  equalPassword() {
    return this.registrationForm.value.password === this.registrationForm.value.passwordConfirmation;
  };

  submitRegistration() {
    const registrationRequest = {
      user: {
        first_name: this.registrationForm.value.firstName,
        last_name: this.registrationForm.value.lastName,
        email: this.registrationForm.value.email,
        password: this.registrationForm.value.password,
        password_confirmation: this.registrationForm.value.passwordConfirmation,
        locale: "en"
      }
    }
    this.userService.createUser(registrationRequest).subscribe(() => { console.log('succes'); });
  };

  ngOnInit() {};
};

<form class="container" [formGroup]="registrationForm" (ngSubmit)="submitRegistration()">
  <div class="form-container log-in">
    <div class="wolox-image">
      <img src="assets/wolox.png" alt="Wolox" >
    </div>
    <div class="input-container">
      <label class="input-label"> First name </label>
      <input class="input-field" type="text" formControlName="firstName">
      <span class="alert" *ngIf="!registrationForm.controls['firstName'].valid && registrationForm.controls['firstName'].touched">
        Required field.
      </span>
    </div>
    <div class="input-container">
      <label class="input-label"> Last name </label>
      <input class="input-field" type="text" formControlName="lastName">
      <span class="alert" *ngIf="!registrationForm.controls['lastName'].valid && registrationForm.controls['lastName'].touched">
        Required field.
      </span>
    </div>
    <div class="input-container">
      <label class="input-label"> Email </label>
      <input class="input-field" type="email" formControlName="email">
      <span class="alert" *ngIf="!registrationForm.controls['email'].valid && registrationForm.controls['email'].touched">
        Required field.
      </span>
      <span class="alert" *ngIf="registrationForm.controls['email'].valid && registrationForm.controls['email'].touched && !validEmail()">
        Invalid format.
      </span>
    </div>
    <div class="input-container">
      <label class="input-label"> Password </label>
      <input class="input-field" type="password" formControlName="password">
      <span class="alert" *ngIf="!registrationForm.controls['password'].valid && registrationForm.controls['password'].touched">
        Required field.
      </span>
    </div>
    <div class="input-container">
      <label class="input-label"> Confirm password </label>
      <input class="input-field" type="password" formControlName="passwordConfirmation">
      <span class="alert" *ngIf="!registrationForm.controls['passwordConfirmation'].valid && registrationForm.controls['passwordConfirmation'].touched">
        Required field.
      </span>
      <span class="alert" *ngIf="registrationForm.controls['passwordConfirmation'].valid && registrationForm.controls['passwordConfirmation'].touched && !equalPassword()">
        Password don't match.
      </span>
    </div>
    <button class="button" type="submit" [disabled]="registrationForm.invalid">Sign up</button>
    <div class="green-button">
      <button class="button empty" routerLink="/login">Log in</button>
    </div>
  </div>
</form>

// wolox-books/src/views/Register.vue
<template lang='pug'>
.container
  form.form-container(@submit.prevent='onSubmit' novalidate)
    img.wolox-image(src='../assets/wolox.png' alt='Wolox')
    .input-container
      label.input-label
        | First name
      input.input-field(type='text' v-model='firstName')
      span.errorMessage(v-if='$v.firstName.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Last name
      input.input-field(type='text' v-model='lastName')
      span.errorMessage(v-if='$v.lastName.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Email
      input.input-field(type='email' v-model='email')
      span.errorMessage(v-if='$v.email.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Password
      input.input-field(type='password' v-model='password')
      span.errorMessage(v-if='$v.password.$invalid && submitted')
        | Invalid field. Upper letters and numbers are required.
    .input-container
      label.input-label
        | Confirm password
      input.input-field(type='password' v-model='confirmPassword')
      span.errorMessage(v-if='$v.confirmPassword.$invalid && submitted')
        | password do not match.
    button.green-button(type='submit')
      | Sign up
    routerLink(to='/login')
      button.grey-button(type='button')
        | Log in
</template>

<script>
import { required, email, sameAs } from 'vuelidate/lib/validators'
import { registerUser } from '../services/user-services'
import validatePassword from '../config/helpers'

export default {
  name: 'register',
  data () {
    return {
      firstName: null,
      lastName: null,
      email: null,
      password: null,
      confirmPassword: null,
      locale: 'en',
      submitted: false
    }
  },
  methods: {
    onSubmit() {
      this.submitted = true
      if (!this.$v.$invalid) {
        const newUserData = {
          first_name: this.firstName,
          last_name: this.lastName,
          email: this.email,
          password: this.password,
          locale: 'en',
          confirm_password: this.confirmPassword
        }
        registerUser(newUserData)
        this.firstName = null
        this.lastName = null
        this.email = null
        this.password = null
        this.confirmPassword = null
        this.submitted = false
      }
    }
  },
  validations: {
    firstName: { required },
    lastName: { required },
    email: { required, email },
    password: { required, validatePassword },
    confirmPassword: { samePassword: sameAs('password') }
  }
}
</script>

<style scoped lang='scss'>
</style>
