// wolox-books/src/app/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators} from '@angular/forms';

const re = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.scss']
})
export class RegisterComponent implements OnInit {

  registrationForm: FormGroup;
  form:any;
  firstName:string = '';
  lastName:string = '';
  email:string = '';
  password:string = '';
  passwordConfirmation:string = '';

  constructor(private fb: FormBuilder) {

    this.registrationForm = fb.group({
      'firstName': [null, Validators.required],
      'lastName': [null, Validators.required],
      'email': [null, Validators.required],
      'password': [null, Validators.required],
      'passwordConfirmation': [null, Validators.required]
    });
  };

  validEmail(emailValue) {
    return re.test(String(emailValue).toLowerCase());
  };

  equalPassword(firstPass, secPass) {
    return firstPass === secPass;
  };

  submitRegistration(form) {
    this.firstName = form.firstName;
    this.lastName = form.lastName;
    this.email = form.email;
    this.password = form.password;
    this.passwordConfirmation = form.passwordConfirmation;

    const registrationRequest = {
      user: {
        first_name: this.firstName,
        last_name: this.lastName,
        email: this.email,
        password: this.password,
        password_confirmation: this.passwordConfirmation,
        locale: "en"
      }
    }
    console.log(registrationRequest);
  };

  ngOnInit() {};
};

<form class="container" [formGroup]="registrationForm" (ngSubmit)="submitRegistration(registrationForm.value)">
  <div></div>
  <div class="formContainer">
    <img src="assets/wolox.png" alt="Wolox" class="woloxImage">

    <div class="inputContainer">
      <label class="inputLabel"> First name </label>
      <input class="inputField" type="text" formControlName="firstName">
      <div class="alert" *ngIf="!registrationForm.controls['firstName'].valid && registrationForm.controls['firstName'].touched">
        Required field.
      </div>
    </div>

    <div class="inputContainer">
      <label class="inputLabel"> Last name </label>
      <input class="inputField" type="text" formControlName="lastName">
      <div class="alert" *ngIf="!registrationForm.controls['lastName'].valid && registrationForm.controls['lastName'].touched">
        Required field.
      </div>
    </div>

    <div class="inputContainer">
      <label class="inputLabel"> Email </label>
      <input class="inputField" type="email" formControlName="email">
      <div class="alert" *ngIf="!registrationForm.controls['email'].valid && registrationForm.controls['email'].touched">
        Required field.
      </div>
      <div class="alert" *ngIf="registrationForm.controls['email'].valid && registrationForm.controls['email'].touched && !validEmail(registrationForm.controls['email'].value)">
        Invalid format.
      </div>
    </div>

    <div class="inputContainer">
      <label class="inputLabel"> Password </label>
      <input class="inputField" type="password" formControlName="password">
      <div class="alert" *ngIf="!registrationForm.controls['password'].valid && registrationForm.controls['password'].touched">
        Required field.
      </div>
    </div>

    <div class="inputContainer">
      <label class="inputLabel"> Confirm password </label>
      <input class="inputField" type="password" formControlName="passwordConfirmation">
      <div class="alert" *ngIf="!registrationForm.controls['passwordConfirmation'].valid && registrationForm.controls['passwordConfirmation'].touched">
        Required field.
      </div>
      <div class="alert" *ngIf="registrationForm.controls['passwordConfirmation'].valid && registrationForm.controls['passwordConfirmation'].touched && !equalPassword(registrationForm.controls['password'].value, registrationForm.controls['passwordConfirmation'].value)">
        Password don't match.
      </div>
    </div>

    <button class="button" type="submit" [disabled]="registrationForm.invalid">Sign up</button>
    <div class="logIn" >
      <button class="button empty">Log in</button>
    </div>

  </div>
</form>
<div></div>

// wolox-books/src/views/Register.vue
<template lang='pug'>
.container
  form.form-container(@submit.prevent='onSubmit' novalidate)
    img.wolox-image(src='../assets/wolox.png' alt='Wolox')
    .input-container
      label.input-label
        | First name
      input.input-field(type='text' v-model='firstName')
      span.errorMessage(v-if='$v.firstName.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Last name
      input.input-field(type='text' v-model='lastName')
      span.errorMessage(v-if='$v.lastName.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Email
      input.input-field(type='email' v-model='email')
      span.errorMessage(v-if='$v.email.$invalid && submitted')
        | Invalid field.
    .input-container
      label.input-label
        | Password
      input.input-field(type='password' v-model='password')
      span.errorMessage(v-if='$v.password.$invalid && submitted')
        | Invalid field. Upper letters and numbers are required.
    .input-container
      label.input-label
        | Confirm password
      input.input-field(type='password' v-model='confirmPassword')
      span.errorMessage(v-if='$v.confirmPassword.$invalid && submitted')
        | password do not match.
    button.green-button(type='submit')
      | Sign up
    routerLink(to='/login')
      button.grey-button(type='button')
        | Log in
</template>

<script>
import { required, email, sameAs } from 'vuelidate/lib/validators'
import { registerUser } from '../services/user-services'
import validatePassword from '../config/helpers'

export default {
  name: 'register',
  data () {
    return {
      firstName: null,
      lastName: null,
      email: null,
      password: null,
      confirmPassword: null,
      locale: 'en',
      submitted: false
    }
  },
  methods: {
    onSubmit() {
      this.submitted = true
      if (!this.$v.$invalid) {
        const newUserData = {
          first_name: this.firstName,
          last_name: this.lastName,
          email: this.email,
          password: this.password,
          locale: 'en',
          confirm_password: this.confirmPassword
        }
        registerUser(newUserData)
        this.firstName = null
        this.lastName = null
        this.email = null
        this.password = null
        this.confirmPassword = null
        this.submitted = false
      }
    }
  },
  validations: {
    firstName: { required },
    lastName: { required },
    email: { required, email },
    password: { required, validatePassword },
    confirmPassword: { samePassword: sameAs('password') }
  }
}
</script>

<style scoped lang='scss'>
</style>
